# Configure Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comenziapi-deployment
spec:
  selector:
    matchLabels:
      app: comenziapi-pod
  template:
    metadata:
      labels:
        app: comenziapi-pod
    spec:
      containers:
      - name: comenziapi-container
        image: mihainegrila.licenta/comenzi.api:1.0.1
        resources:
          limits:
            memory: "128Mi" # 128 mili bytes
            cpu: "500m"     # 500 mili cpu
        ports:
        - containerPort: 80